Ruby Blog: Validation and Spec
AmanWorku/Rails-Blog pull request #3
Opened 2023-04-12 15:22 UTC by AmanWorku

## Hey there....
![](https://media.giphy.com/media/icUEIrjnUuFCWDxFpU/giphy.gif)
# In this PR I:
- [x] Added validations for the User model
- [x] Added validations for the Post model with requirements given.
- [x] Added unit specs for all of the models' methods and validations.  

_Cheers🥂_

2023-04-12 15:36 UTC, Ismailco requested changes
### Hi @AmanWorku, 

Good job so far 👍🏼 
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights

✔️ No linter errors
✔️ Used Gitflow
✔️ Work documented professionally

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers, and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-04-12 15:36 UTC, Ismailco commented on spec/model/user_spec.rb
> +RSpec.describe User, type: :model do
- [ ] Any custom methods in the `User` model should have a corresponding unit test, kindly make sure to implement tests for the `recent_three_posts` your Model is fully tested

2023-04-12 15:36 UTC, Ismailco commented on spec/model/user_spec.rb
> +  end
- [ ] [OPTIONAL] Kindly make sure to include more cases in your unit tests, like when the user is present, post_conter has a valid value (positive number)...

2023-04-12 15:36 UTC, Ismailco commented on spec/model/post_spec.rb
> +RSpec.describe Post, type: :model do
- [ ] Same here, any custom methods in the `Post` model should have a corresponding unit test, kindly make sure to implement tests for the `update_posts_count` your Model is fully tested

2023-04-12 15:36 UTC, Ismailco commented on spec/model/like_spec.rb
> +RSpec.describe Like, type: :model do
- [ ] Kindly make sure to include tests for `update_like_count` method so your Model is fully tested

2023-04-12 15:36 UTC, Ismailco commented on spec/model/comment_spec.rb
> +RSpec.describe Comment, type: :model do
- [ ] Kindly make sure to include tests for `update_comment_count` method so your Model is fully tested

2023-04-13 06:43 UTC, CollinsTatang approved these changes
# Approved 👏  
### **Highlights 🚀 :heavy_check_mark: :heavy_check_mark:** 

- The repo looks professional.:heavy_check_mark:
- Git/GitHub flow best practices have been followed:heavy_check_mark:
- You have descriptive PR:heavy_check_mark:
- Great job implementing all the required tests changes requested by the previous reviewer :heavy_check_mark: 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
### **Congratulations!** 🎉 
![image](https://user-images.githubusercontent.com/25227022/165483662-7b06c812-4cc0-40b9-a84c-4729d4cf10c3.gif)



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag @CollinsTatang in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-04-13 06:50 UTC, AmanWorku commented
Thank you so much @CollinsTatang. Have a great day.

2023-04-13 06:50 UTC, merged