Rails Blog: Forms
AmanWorku/Rails-Blog pull request #7
Opened 2023-04-21 15:03 UTC by AmanWorku

## Hey there....
![](https://media.giphy.com/media/l3vR7PTT3BZlTg7As/giphy.gif)
# In this pull request I: 
- [x] Created a method called `current_user` in my ApplicationController to make current user data available to all controllers.
- [x] Assigned the first user to be the current user as there is no authentication.
- [x] Created methods for forms to perform creating new posts and a new comments on behalf of the current user.
- [x] Allowed all users to add likes to posts.

## - Screenshot attached below: 
![Screenshot 2023-04-21 at 6 02 22 PM](https://user-images.githubusercontent.com/80094659/233669564-df28bc6e-eb91-4dd0-9e50-62e2c54f9dd3.png)
![Screenshot 2023-04-21 at 6 02 31 PM](https://user-images.githubusercontent.com/80094659/233669570-dbcae781-6f3c-4536-b173-0ade8a6c0137.png)

2023-04-21 15:46 UTC, Felix45 requested changes
Hi @AmanWorku , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

<img src="https://user-images.githubusercontent.com/20563252/121369265-4e418880-c901-11eb-848c-1eff06d5a4cf.gif" width="375px" />

## Highlights :heavy_check_mark: 
- [x] No linter errors :white_check_mark: 
- [x] Good code and file organization :white_check_mark: 
- [x]  Pull request has a descriptive summary and title :white_check_mark: 
- [x] Repository has a professional readme file :white_check_mark:   

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-04-21 15:46 UTC, Felix45 commented on app/controllers/posts_controller.rb
>    end
- [Required] I think it would be better if you fix this issue when creating a post from the form, I encountered the error below I think this is because of line `21` since the user model has no field called `index`. Please ensure the create post method should work properly without error.

- [Optional] I think it would be better if you used strong parameters in your controllers, this will prevent users from assigning parameters to your controller methods unless they have been explicitly permitted. I'll leave you this link and a code snippet below for more information on this [click here >>](https://github.com/microverseinc/curriculum-rails/blob/main/blog-app/lessons/Controllers_lesson.md#:~:text=Pay%20special%20attention%20to%20the%20strong%20parameters%20description%20in%20Rails%20Guides.)

```ruby
# Optional

  class PostsController < ApplicationController

    def new
      @post = Post.new
    end

    def create
      @post = @current_user.posts.new(post_params)

      respond_to do |format|
        if @post.save
          format.html { redirect_to @post }
        else
          format.html { render :new }
        end
      end
   end

  private 
 
  def post_params
    params.require(:post).permit(:title, :text)
  end
end

```

## Error
![Screenshot from 2023-04-21 18-13-29](https://user-images.githubusercontent.com/16392046/233673891-4148387b-7d9d-464a-a2fc-607757728475.png)

2023-04-21 15:46 UTC, Felix45 commented on app/controllers/comments_controller.rb
> +  end
- [Optional] I think it would be better if you used strong parameters in your comments controllers, this will prevent users from assigning parameters to your controller methods unless they have been explicitly permitted. I'll leave you this link and a code snippet below for more information on this [click here >>](https://github.com/microverseinc/curriculum-rails/blob/main/blog-app/lessons/Controllers_lesson.md#:~:text=Pay%20special%20attention%20to%20the%20strong%20parameters%20description%20in%20Rails%20Guides.)

```ruby
class CommentsController < ApplicationController

  def new
    @comment = Comment.new
  end

	def create
    @comment = @current_user.comments.new(params)
    @comment.post_id = params[:post_id]

    if @comment.save
      redirect_to post_path(@comment.post)
    else
      @article = Post.find(params[:post_id])
      redirect_to post_path(@post)
    end
  end

  private 

  def comment_params
    params.require(:comment).permit(:text)
  end
end
```

2023-04-21 20:02 UTC, AmanWorku commented
@Felix45 Thank you so much sir. Will do that accordingly.

2023-04-22 04:35 UTC, FrederickMih approved these changes
## Hi :raising_hand:  @AmanWorku, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 


## Highlights :green_circle: 

- PR is professional :+1: 
- Good commit history :+1: 
- Linter checks passed :heavy_check_mark: 



_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers, and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-04-22 04:38 UTC, AmanWorku commented
@FrederickMih Thank you!

2023-04-22 04:39 UTC, merged